apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgC3Vj9W76el/bJemj73KqytDQs9RxtJrdlFcWOLY0BFQjfOPtQWsD/3XrQpzzkHBgSK2k92MprA5E0vcEGEfiGg77+vxVIIGtb2c7tEEdHZ7JafBPCpHfEg26SBrfWBNyGIBUiI3EJ06e4x4lVw66i7JcdEvOG3o+doOIOflUcqKCz1LfoQur5ggabgf2ikfpsz/sls/mg6iosS0l4ddkmQlR0V+2DuSBfI10TlX3KM43CXLFNgywQcm2wzD4Ndm1iw1SU/C0MCGfQ3DDYzq3UnuDvst2zUIOn0qngIBFKMtoEsBghMIwGJUjweBjFLEMU5fmOSsypmpHv18uPhDfM5EUCjqacpHa8kGaJZ/pV9jZ8MjrmiiAvltoyYeJ6/bAKdEs+PesT72ME3QExkufGpizgPVvhcNvh/tGK2v8dcSClexjYDypHrytmsSQyjnil2eLO2+subbbd0mjd+1MwE2cTb/EnKzvlzwsgZHTqjNRC2+l8xockcY0EDP0Xl4f3u1wuDf+8kiNgIMIcoWLBKFCksijOYhpm07OvQL6Am/IQv6jhj+xKutvsHrFzUyJ7YDmXWxGphlqqZeS3kSXL78NzeB3dMXWzC7AIELwQKci06ZwKt931MBR6SWn9ODnXChzRSsvnSpdbIiE8fp5gB5W4IgqzvR+2Aat3oDYkQ1B7YIdoVtJL832vcNhn9ScvMqjaLwKIBxVtJPFJGEksOM+ImAQGScSI6/vgsNS3mexefBWllIMYOBZ6GAd92lKw=
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
