authentik:
  authentik:
    existingSecret:
      secretName: authentik-secrets
    error_reporting:
      enabled: false
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
      hosts:
        - auth.duylai.duckdns.org
      tls:
        - hosts:
            - auth.duylai.duckdns.org
          secretName: authentik-tls
  postgresql:
    enabled: true
    auth:
      existingSecret: authentik-postgresql-secret
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: password
  redis:
    enabled: true
