---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vikunja-secrets
  namespace: vikunja
spec:
  encryptedData:
    VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTSECRET: AgBZ8W9qOK5pqK3g665nJeGdMfihuCaAfl6ti6mTTOQhCuWT9pdt89Mix/fzIkHQdj8AJoCYpmN+vBvDh84YzPov2KoQuSAXZVL/jdWa/1DgpBjFx4bP8mbNQkFa5zwBBOzl6I4Oxu5IJSTHhyrnnrt+RIEdN4Oe6lXK3ivmsJeVlgEZty1EkHveOjS4rLFZfViFIPy2uBH8FsxZq44y9BF2Ti21ToGy2lXkSuslYyHZW4vCSSpbdM50fM6Uy/lQkRu9uAcrLMRcDwHt1H7YC9d2P0Leyt+pHbvFwrDoli5vibaX2Mo0abE6KX7/kEK7WF2N7E8J8553mGrNIuhjTUQ8M0bIVnP8j0oFqNPPGKxpGcou3yLQNRaP68YrNLTbRKyLheUV2Ihvmho6euUu15kYMGq0T4Ko8u2NHA9j1ou3+uUlp4gfuHXyHm0pvrvJ5vj7aEtChhHaGUZ62RtM7lNLmyTIt3ToNFEtOc9jFBVgqjbxE0Rnwa30CccdeEeKEWfSeusEK4x3UbTFWgc9o2CULRw3oppEkXtbhU1mWOE4D4FRN6ruFV+TLnQQOGneVGfbJMgKLnOY9jH1YO0nhFq1Vaj5EyW4uUAJl3/JU0P1T26ILJQwltbVuftzomFBPqBP+66jtGCbrqdnbDcg+sn8xwSSAIj9dX53uVFJ0DntGbjfNHze9MIq/tv4DN5Ox61dF9wwQYREBi1Z19fexCJVigTdaqlcOiXh0PUt4i54VJx2VF5Eds1qjhA7KiNVcixjoSp2oXugBUvDHvuPvlwQcfzTKkksbZVUN7jZ3vuKHse+2+asH3tCQCE0KNTSUQwRnQ4Zmp+pVgokkrporzVu+4kziH2OQxZu0PzJaG7ilA==
  template:
    metadata:
      creationTimestamp: null
      name: vikunja-secrets
      namespace: vikunja
