apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../infrastructure
  - ../../apps/headlamp/application.yaml
  - ../../apps/vikunja/application.yaml
  - ../../apps/gitea/application.yaml
