apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-roamflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/laiduy98/devops.git
    targetRevision: main
    path: clusters/roamflow
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
