gitea:
  gitea:
    config:
      server:
        ROOT_URL: "https://gitea.duylai.duckdns.org/"
        SSH_DOMAIN: "gitea.duylai.duckdns.org"
        SSH_PORT: 30222
      service:
        DISABLE_REGISTRATION: false
        ALLOW_ONLY_EXTERNAL_REGISTRATION: true
        SHOW_REGISTRATION_BUTTON: false
      oauth2_client:
        ENABLE_AUTO_REGISTRATION: true
        ACCOUNT_LINKING: auto
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
    hosts:
      - host: gitea.duylai.duckdns.org
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - gitea.duylai.duckdns.org
        secretName: gitea-tls-secret
  service:
    ssh:
      type: NodePort
      port: 22
      nodePort: 30222
